name: phoenix_wings_allow_any
description: Phoenix Channel client for Dart
version: 1.0.0
homepage: https://github.com/kinhchendev/phoenix_wings_allow_any

dev_dependencies:
  test: ^1.17.5
  mockito: ^5.0.9
  stream_channel: ^2.1.0
  intl: ^0.17.0
  build_runner: ^2.0.4

environment:
  sdk: ">=2.12.0 <3.0.0"
